### ISSUE TITLE
URL not functional

### ISSUE THREAD

**Issue by ShouraySolanki** [manishmeganathan/AudioServer#2]

**Comment by manishmeganathan** [comment]
The URL is **still functional** but clicking on it will throw a *404* code because the bare URL is just the root.

You would need to try one of the complete URL along with one of the supported methods. Please refer to the README section titled [**AudioServer API**](https://github.com/manishmeganathan/AudioServer#audioserver-api) for more information. 
Please feel free to expand on this issue or open a new one if you feel the documentation provided is insufficient.

Here's an example of a URL structure that will work by simply clicking on it (The GET method is implemented for this endpoint):
https://audioserver-3wow3hatda-de.a.run.app/get/audiobook
You can swap out the *audiobook* argument for *song* or *podcast* and you should have similar results

**note**: This project and the URL was never designed to be used in a browser. you are gonna have a better time working with by using tools like cURL or an application like Postman (personally I prefer Postman)

**Comment by ShouraySolanki** [comment]
could you please give an example of create functionality

**Comment by manishmeganathan** [comment]
@Thepunisher64344 

That would look something like **https://audioserver-3wow3hatda-de.a.run.app/create/song**
and you would hit with a ``POST`` method with some JSON data payload in the following format.
```
{
    "name": "some arbitrary song name",  
    "duration": 35,
}
```
